import click

from qivo.settings import Migrations, SQLAlchemy
from sqlalchemy import create_engine

from qivo.cli.migrate.base import AlembicMigrations, MigrationConfig
from qivo.utils import import_symbol


def _load_migrations():
    db = SQLAlchemy.from_toml("qivo.toml")
    migrations = Migrations.from_toml("qivo.toml")
    engine = create_engine(db.url, **db.engine_options)
    bases = [import_symbol(base).metadata for base in migrations.model_bases]
    return AlembicMigrations(
        engine,
        bases,
        MigrationConfig(
            directory=migrations.directory,
            compare_type=migrations.compare_type,
            render_as_batch=migrations.render_as_batch,
        ),
    )


@click.command("migrate")
@click.option("-m", "--message", default="autogenerated", show_default=True)
@click.option(
    "--empty", is_flag=True, help="Create a blank migration without autogeneration."
)
def migrate(message: str, empty: bool):
    alembic = _load_migrations()
    alembic.revision(message, autogenerate=not empty)


@click.command("migrate:apply")
@click.argument("revision", required=False, default="head")
def migrate_apply(revision: str):
    alembic = _load_migrations()
    alembic.upgrade(revision)


@click.command("migrate:revert")
@click.argument("revision", required=False, default="-1")
def migrate_revert(revision: str):
    alembic = _load_migrations()
    alembic.downgrade(revision)


commands = [migrate, migrate_apply, migrate_revert]